<?xml version="1.0" ?>

<robot name="eboat" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- base_link (eboat_core/hull) -->
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="eboat.gazebo"/>

  <!-- Import Rviz colors -->
  <xacro:include filename="materials.xacro"/>

  <!-- Include macros for dynamics plugins -->
  <xacro:include filename="$(find eboat_description)/urdf/macros.xacro"/>

  <!-- Attach hydrodynamics plugin -->
  <xacro:usv_dynamics_gazebo name="seboat_dynamics_plugin"/>

  <!-- Attach lift&drag plugin for sail -->
  <xacro:eboat_sail_gazebo name="eboat_sail"/>

  <!-- Attach lift&drag plugin for the windsock -->
  <xacro:eboat_biruta_gazebo name="eboat_biruta"/>

  <link name="base_link">
    <origin xyz="0 0 0" rpy="0 0 0" />
  </link>

  <joint name="dummy_joint" type="fixed">
      <parent link="base_link"/>
      <child link="hull_link"/>
      <!-- Adjust the visual/collision to match water height -->
      <origin xyz="0 0 0.210586" rpy="0 0 0"/>
  </joint>

  <link name="hull_link">
    <visual>
      <origin xyz="-1.24471 0 0.199376" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/hull.dae"/>
      </geometry>
      <material name="hull_link_material">
        <color rgba="0.0862745 0.317647 0.690196 1.0"/>
      </material>
    </visual>
    <!--<collision>
      <origin xyz="-1.24471 1.33227e-15 0.199376" rpy="0 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/hull.stl"/>
      </geometry>
    </collision>-->
    <collision>
      <origin xyz="0.05 0 0.075" rpy="0 0 0" />
      <geometry>
        <box size="2.7 1.0 0.63"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="-0.223902 3.01748e-05 -0.0663978" rpy="0 0 0"/>
      <mass value="77.4684" />
      <inertia ixx="6.90566" ixy="0.00469505"  ixz="1.80482" iyy="40.7994" iyz="-0.000726059" izz="44.4125" />
    </inertial>
  </link>

  <link name="bow">
    <visual>
      <origin xyz="0.0 0.19871 -2.48942" rpy="-1.5708 -1.5708 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/bow.dae"/>
      </geometry>
      <material name="bow_material">
        <color rgba="0 0 0 1.0"/>
      </material>
    </visual>
    <!--<collision>
      <origin xyz="2.03223e-15 0.19871 -2.48942" rpy="-1.5708 -1.5708 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/bow.stl"/>
      </geometry>
    </collision>-->
    <inertial>
      <origin xyz="0.0 0.0 0.0331645" rpy="0 0 0"/>
      <mass value="2.74292" />
      <inertia ixx="0.00385807" ixy="1.73947e-24"  ixz="-1.33071e-08" iyy="0.0386673" iyz="-2.13558e-09" izz="0.0373952" />
    </inertial>
  </link>

  <joint name="bow_joint" type="fixed">
      <origin xyz="1.24471 0.0 0.000666379" rpy="1.5708 -0 1.5708" />
    <parent link="hull_link" />
    <child link="bow" />
    <!--<axis xyz="0 0 1"/>-->
    <limit effort="1" velocity="20" />
    <joint_properties friction="0.0"/>
  </joint>

  <link name="espuma">
    <visual>
      <origin xyz="-2.48442 0 0.39742" rpy="0 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/espuma.dae"/>
      </geometry>
      <material name="espuma_material">
        <color rgba="0.980392 0.796078 0.262745 1.0"/>
      </material>
    </visual>
    <!--<collision>
      <origin xyz="-2.48442 0 0.39742" rpy="0 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/espuma.dae"/>
      </geometry>
    </collision>-->
    <inertial>
      <origin xyz="-1.46006 6.62141e-08 0.0160186" rpy="0 0 0"/>
      <mass value="2.57637" />
      <inertia ixx="0.108083" ixy="5.88834e-08"  ixz="0.0367853" iyy="1.02049" iyz="3.28703e-09" izz="1.12239" />
    </inertial>
  </link>

  <joint name="espuma_joint" type="fixed">
    <origin xyz="1.23971 1.33227e-15 -0.193335" rpy="0 -0 0" />
    <parent link="hull_link" />
    <child link="espuma" />
    <!--<axis xyz="0 0 1"/>-->
    <limit effort="1" velocity="20" />
    <joint_properties friction="0.0"/>
  </joint>

  <link name="gate_1">
    <visual>
      <origin xyz="7.75088e-17 0.164636 -0.465" rpy="-1.5708 -1.5708 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/gate_1.stl"/>
      </geometry>
      <material name="gate_1_material">
        <color rgba="1 1 1 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="7.75088e-17 0.164636 -0.465" rpy="-1.5708 -1.5708 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/gate_1.stl"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="4.82287e-17 0 1.66533e-16" rpy="0 0 0"/>
      <mass value="0.230009" />
      <inertia ixx="0.0140033" ixy="0"  ixz="0" iyy="0.0161788" iyz="0" izz="0.00217652" />
    </inertial>
  </link>

  <joint name="gate_1_joint" type="fixed">
      <origin xyz="-0.77971 1.25476e-15 0.0347405" rpy="1.5708 -0 1.5708" />
    <parent link="hull_link" />
    <child link="gate_1" />
    <!--<axis xyz="0 0 1"/>-->
    <limit effort="1" velocity="20" />
    <joint_properties friction="0.0"/>
  </joint>

  <link name="gate_2">
    <visual>
      <origin xyz="1.00289e-16 0.187569 -0.96" rpy="-1.5708 -1.5708 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/gate_2.stl"/>
      </geometry>
      <material name="gate_2_material">
        <color rgba="1 1 1 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="1.00289e-16 0.187569 -0.96" rpy="-1.5708 -1.5708 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/gate_2.stl"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="-4.80661e-17 -1.11022e-16 0" rpy="0 0 0"/>
      <mass value="0.269837" />
      <inertia ixx="0.017345" ixy="0"  ixz="0" iyy="0.0206748" iyz="0" izz="0.00333089" />
    </inertial>
  </link>

  <joint name="gate_2_joint" type="fixed">
      <origin xyz="-0.28471 1.23198e-15 0.0118069" rpy="1.5708 -0 1.5708" />
    <parent link="hull_link" />
    <child link="gate_2" />
    <!--<axis xyz="0 0 1"/>-->
    <limit effort="1" velocity="20" />
    <joint_properties friction="0.0"/>
  </joint>

  <link name="gate_3">
    <visual>
      <origin xyz="-1.27365e-16 0.188535 -1.835" rpy="-1.5708 -1.5708 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/gate_3.stl"/>
      </geometry>
      <material name="gate_3_material">
        <color rgba="1 1 1 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="-1.27365e-16 0.188535 -1.835" rpy="-1.5708 -1.5708 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/gate_3.stl"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="-2.23868e-17 -0.000875031 -2.22045e-16" rpy="0 0 0"/>
      <mass value="0.223381" />
      <inertia ixx="0.0041687" ixy="0"  ixz="0" iyy="0.00692788" iyz="0" izz="0.00290898" />
    </inertial>
  </link>

  <joint name="gate_3_joint" type="fixed">
      <origin xyz="0.59029 1.34861e-15 0.0141716" rpy="1.5708 -0 1.5708" />
    <parent link="hull_link" />
    <child link="gate_3" />
    <!--<axis xyz="0 0 1"/>-->
    <limit effort="1" velocity="20" />
    <joint_properties friction="0.0"/>
  </joint>

  <link name="deck_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/deck.stl"/>
      </geometry>
      <material name="deck_material">
        <color rgba="1 1 1 1.0"/>
      </material>
    </visual>
    <!--<collision>
      <origin xyz="0 0 0" rpy="0 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/deck.stl"/>
      </geometry>
    </collision>-->
    <inertial>
      <origin xyz="1.10267 0.00505112 0.0298862" rpy="0 0 0"/>
      <mass value="4.65558" />
      <inertia ixx="0.384796" ixy="0.0209115"  ixz="0.00217436" iyy="1.95434" iyz="0.000402869" izz="2.33348" />
    </inertial>
  </link>

  <xacro:support_hack name="port_1" xyz="-0.0410859 -0.407092 -0.05" rpy="0 0 0" />
  <xacro:support_hack_joint name="port_1" xyz="0.0410859 0.407092 0.05" rpy="0 0 0" />

  <xacro:support_hack name="port_2" xyz="-0.776847 -0.466397 -0.05" rpy="0 0 0" />
  <xacro:support_hack_joint name="port_2" xyz="0.776847 0.466397 0.05" rpy="0 0 0" />

  <xacro:support_hack name="port_3" xyz="-1.58684 -0.364972 -0.05" rpy="0 0 0" />
  <xacro:support_hack_joint name="port_3" xyz="1.58684 0.364972 0.05" rpy="0 0 0" />

  <xacro:support_hack name="port_4" xyz="-2.44761 -0.0712925 -0.05" rpy="0 0 0" />
  <xacro:support_hack_joint name="port_4" xyz="2.44761 0.0712925 0.05" rpy="0 0 0" />

  <link name="hack_port">
    <visual>
      <origin xyz="-2.25991 0.14 -0.976456" rpy="1.5708 -0.372391 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/hack_port.stl"/>
      </geometry>
      <material name="hack_port_material">
        <color rgba="0.843137 0.847059 0.843137 1.0"/>
      </material>
    </visual>
    <!--<collision>
      <origin xyz="-2.25991 0.14 -0.976456" rpy="1.5708 -0.372391 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/hack_port.stl"/>
      </geometry>
    </collision>-->
    <inertial>
      <origin xyz="-1.21936 -0.00999996 -0.172168" rpy="0 0 0"/>
      <mass value="1.73166" />
      <inertia ixx="0.145762" ixy="0.30743"  ixz="-0.11944" iyy="0.812703" iyz="0.0466561" izz="0.907836" />
    </inertial>
  </link>

  <joint name="hack_port_joint" type="fixed">
      <origin xyz="0.0126828 0.0159808 0.0899999" rpy="-1.5708 -1.50078e-14 -0.372391" />
    <parent link="support_hack_port_4_link" />
    <child link="hack_port" />
    <!--<axis xyz="0 0 1"/>-->
    <limit effort="1" velocity="20" />
    <joint_properties friction="0.0"/>
  </joint>

  <xacro:support_hack name="starboard_1" xyz="-0.0410859 0.407092 -0.05" rpy="0 0 0" />
  <xacro:support_hack_joint name="starboard_1" xyz="0.0410859 -0.407092 0.05" rpy="0 0 0" />

  <xacro:support_hack name="starboard_2" xyz="-0.776847 0.466397 -0.05" rpy="0 0 0" />
  <xacro:support_hack_joint name="starboard_2" xyz="0.776847 -0.466397 0.05" rpy="0 0 0" />

  <xacro:support_hack name="starboard_3" xyz="-1.58684 0.364972 -0.05" rpy="0 0 0" />
  <xacro:support_hack_joint name="starboard_3" xyz="1.58684 -0.364972 0.05" rpy="0 0 0" />

  <xacro:support_hack name="starboard_4" xyz="-2.44761 0.071293 -0.05" rpy="0 0 0" />
  <xacro:support_hack_joint name="starboard_4" xyz="2.44761 -0.071293 0.05" rpy="0 0 0" />

  <link name="hack_starboard">
    <visual>
      <origin xyz="-2.25991 -0.14 -0.976456" rpy="-1.5708 -0.372391 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/hack_starboard.stl"/>
      </geometry>
      <material name="hack_starboard_material">
        <color rgba="0.843137 0.847059 0.843137 1.0"/>
      </material>
    </visual>
    <!--<collision>
      <origin xyz="-2.25991 -0.14 -0.976456" rpy="-1.5708 -0.372391 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/hack_starboard.stl"/>
      </geometry>
    </collision>-->
    <inertial>
      <origin xyz="-1.21884 0.00999997 -0.171992" rpy="0 0 0"/>
      <mass value="1.73089" />
      <inertia ixx="0.145604" ixy="-0.307035"  ixz="-0.119393" iyy="0.8117" iyz="-0.046636" izz="0.906679" />
    </inertial>
  </link>

  <joint name="hack_starboard_joint" type="fixed">
      <origin xyz="0.0126838 -0.0159804 0.0900001" rpy="1.5708 2.52146e-14 0.372391" />
    <parent link="support_hack_starboard_4_link" />
    <child link="hack_starboard" />
    <!--<axis xyz="0 0 1"/>-->
    <limit effort="1" velocity="20" />
    <joint_properties friction="0.0"/>
  </joint>

  <joint name="deck_joint" type="fixed">
      <origin xyz="-1.24471 1.33227e-15 0.199376" rpy="0 -0 0" />
    <parent link="hull_link" />
    <child link="deck_link" />
    <!--<axis xyz="0 0 1"/>-->
    <limit effort="1" velocity="20" />
    <joint_properties friction="0.0"/>
  </joint>

  <xacro:property name="mlength" value="${0.45+2.9+0.2}"/> <!--set the length of the main sail mast-->
  <link name="mast_link">
    <visual>
      <origin xyz="0 -2.14313e-18 0.933" rpy="0 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/mast_link.stl"/>
      </geometry>
      <material name="mast_link_material">
        <color rgba="0.301961 0.301961 0.301961 1.0"/>
      </material>
    </visual>
    <!--<collision>
      <origin xyz="0 -2.14313e-18 0.933" rpy="0 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/mast_link.stl"/>
      </geometry>
    </collision>-->
    <collision>
      <origin xyz="0 0 ${0.45+mlength*0.5}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.05" length="${mlength}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="-7.06046e-05 -3.75196e-07 1.86842" rpy="0 0 0"/>
      <mass value="11.9114" />
      <inertia ixx="13.8832" ixy="-1.80332e-07"  ixz="-0.0005826" iyy="13.8832" iyz="-3.34628e-06" izz="0.0168395" />
    </inertial>
  </link>

  <!--<joint name="mast_joint" type="fixed">
      <origin xyz="0.59029 1.55646e-15 -0.172694" rpy="0 -0 0" />
    <parent link="hull_link" />
    <child link="mast_link" />
    <axis xyz="0 0 1"/>
    <limit effort="1" velocity="20" />
    <joint_properties friction="0.0"/>
  </joint>-->

  <joint name="mast_joint" type="fixed">
      <origin xyz="0.59029 1.55646e-15 -0.172694" rpy="0 -0 0" />
    <parent link="hull_link" />
    <child link="mast_link" />
    <axis xyz="1 0 0"/>
    <limit effort="0" velocity="0" upper="0" lower="0"/>
  </joint>

  <link name="keel_link">
    <visual>
      <origin xyz="0 -4.51028e-17 -0.98067" rpy="0 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/keel.stl"/>
      </geometry>
      <material name="keel_link_material">
        <color rgba="1 1 1 1.0"/>
      </material>
    </visual>
    <!--<collision>
      <origin xyz="0 -4.51028e-17 -0.98067" rpy="0 -0 0" />
      <geometry>
      <mesh filename="package://eboat_description/models/eboat/meshes/keel.stl"/>
      </geometry>
    </collision>-->
    <collision>
      <origin xyz="0 0 -0.5635" rpy="0 -0 0" />
      <geometry>
      <box size="0.459 0.124 1.127"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.00547163 2.63588e-07 -0.725086" rpy="0 0 0"/>
      <mass value="40.0429" />
      <inertia ixx="5.03511" ixy="7.80906e-07"  ixz="-0.0285151" iyy="5.27158" iyz="-2.96682e-06" izz="0.268882" />
    </inertial>
  </link>

  <joint name="keel_joint" type="revolute">
    <origin xyz="-0.14471 1.41206e-15 -0.0106236" rpy="0 -0 1.83666e-16" />
    <parent link="hull_link" />
    <child link="keel_link" />
    <axis xyz="0 0 1"/>
    <limit effort="1" velocity="20" lower="0" upper="0"/>
    <joint_properties friction="0.0"/>
  </joint>

  <link name="rudder_link">
    <visual>
      <origin xyz="-0.02365 -2.14313e-19 -0.91802" rpy="0 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/rudder.stl"/>
      </geometry>
      <material name="rudder_link_material">
        <color rgba="0.901961 0.901961 0.901961 1.0"/>
      </material>
    </visual>
    <!--<collision>
      <origin xyz="-0.02365 -2.14313e-19 -0.91802" rpy="0 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/rudder.stl"/>
      </geometry>
    </collision>-->
    <collision>
      <origin xyz="0 0 ${-0.310-0.304}" rpy="0 0 0" />
      <geometry>
        <box size="0.189 0.015 0.608"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="-0.00641724 -6.72693e-06 -0.592315" rpy="0 0 0"/>
      <mass value="1.60989" />
      <inertia ixx="0.0537961" ixy="-3.12873e-06"  ixz="-0.00207534" iyy="0.0565408" iyz="-5.88255e-07" izz="0.00276589" />
    </inertial>
  </link>

  <joint name="rudder_joint" type="revolute">
      <origin xyz="-1.09141 1.33248e-15 0.144376" rpy="0 -0 0" />
    <parent link="hull_link" />
    <child link="rudder_link" />
    <axis xyz="0 0 1"/>
    <limit effort="50" velocity="${24.0*(3.1415/180.0)}" lower="-1.0472" upper="1.0472"/>
    <dynamics damping="0.0" friction="2.0"/>
  </joint>

  <link name="boom_link">
    <visual>
      <origin xyz="-0.0248 0 0" rpy="0 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/boom.stl"/>
      </geometry>
      <material name="boom_link_material">
        <color rgba="0.301961 0.301961 0.301961 1.0"/>
      </material>
    </visual>
    <!--<collision>
      <origin xyz="-0.0248 0 0" rpy="0 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/boom.stl"/>
      </geometry>
    </collision>-->
    <collision>
      <origin xyz="${-0.9-0.0248} 0 0" rpy="0 -1.5708 0" />
      <geometry>
        <cylinder radius="0.02" length="1.8"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="-0.920621 5.2117e-10 1.56762e-05" rpy="0 0 0"/>
      <mass value="2.40594" />
      <inertia ixx="0.000426047" ixy="-7.43982e-10"  ixz="3.31727e-05" iyy="0.663048" iyz="2.03872e-11" izz="0.663047" />
    </inertial>
  </link>

  <link name="rope_c">
    <visual>
      <origin xyz="1.773 -0.0223 0" rpy="-1.5708 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/rope_c.stl"/>
      </geometry>
      <material name="rope_c_material">
        <color rgba="0.65098 0.486275 0.0196078 1.0"/>
      </material>
    </visual>
    <!--<collision>
      <origin xyz="1.773 -0.0223 0" rpy="-1.5708 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/rope_c.stl"/>
      </geometry>
    </collision>-->
    <!--<inertial>
      <origin xyz="0.00703696 0.0220581 -3.20557e-09" rpy="0 0 0"/>
      <mass value="0.00291411" />
      <inertia ixx="7.3389e-07" ixy="1.82337e-07"  ixz="9.94702e-13" iyy="2.20535e-07" iyz="-2.97602e-12" izz="6.38804e-07" />
    </inertial>-->
  </link>

  <link name="sail_link">
    <visual>
      <origin xyz="1.75893 -0.0664151 0" rpy="-1.5708 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/sail.stl"/>
      </geometry>
      <material name="sail_material">
        <color rgba="1 1 1 1.0"/>
      </material>
    </visual>
    <!--<collision>
      <origin xyz="1.75893 -0.0664151 0" rpy="-1.5708 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/sail.stl"/>
      </geometry>
    </collision>-->
    <!--<inertial>
      <origin xyz="1.10322 1.09346 -1.3549e-20" rpy="0 0 0"/>
      <mass value="2.216" />
      <inertia ixx="1.15797" ixy="0.243689"  ixz="0" iyy="0.386027" iyz="0" izz="1.544" />
    </inertial>-->
  </link>

  <link name="rope_b">
    <visual>
      <origin xyz="0.01 -0.066 0" rpy="-1.5708 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/rope_b.stl"/>
      </geometry>
      <material name="rope_b_material">
        <color rgba="0.65098 0.486275 0.0196078 1.0"/>
      </material>
    </visual>
    <!--<collision>
      <origin xyz="0.01 -0.066 0" rpy="-1.5708 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/rope_b.stl"/>
      </geometry>
    </collision>-->
    <!--<inertial>
      <origin xyz="0.018251 -0.000499947 -8.97391e-08" rpy="0 0 0"/>
      <mass value="0.00246085" />
      <inertia ixx="1.44187e-07" ixy="-9.66902e-09"  ixz="8.52088e-12" iyy="4.96841e-07" iyz="2.27511e-13" izz="3.60873e-07" />
    </inertial>-->
  </link>

  <joint name="rope_b_joint" type="fixed">
      <origin xyz="1.74893 -0.000415051 0" rpy="0 -0 0" />
    <parent link="sail_link" />
    <child link="rope_b" />
    <!--<axis xyz="0 0 1"/>-->
    <limit effort="1" velocity="20" />
    <joint_properties friction="0.0"/>
  </joint>

  <joint name="rope_c_joint_1" type="fixed">
      <origin xyz="0.0140742 0.0441151 0" rpy="0 -0 0" />
    <parent link="rope_c" />
    <child link="sail_link" />
    <!--<axis xyz="0 0 1"/>-->
    <limit effort="1" velocity="20" />
    <joint_properties friction="0.0"/>
  </joint>

  <joint name="rope_c_joint_2" type="fixed">
      <origin xyz="-1.7978 0 0.0223" rpy="1.5708 -0 0" />
    <parent link="boom_link" />
    <child link="rope_c" />
    <!--<axis xyz="0 0 1"/>-->
    <limit effort="1" velocity="20" />
    <joint_properties friction="0.0"/>
  </joint>

  <joint name="boom_joint" type="revolute">
      <origin xyz="0.54129 1.44329e-15 0.760306" rpy="0 -0 0" />
    <parent link="hull_link" />
    <child link="boom_link" />
    <axis xyz="0 0 1"/>
    <limit effort="1000" velocity="5" lower="-1.5708" upper="1.5708"/>
    <!--<limit effort="1000" velocity="0.6" lower="-1.5708" upper="1.5708"/>-->
    <dynamics damping="2.0" friction="0.0"/>
  </joint>

  <link name="boom_rope_link">
    <visual>
      <origin xyz="0.314665 0 -0.247894" rpy="0 0.721157 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/boom_rope.stl"/>
      </geometry>
      <material name="boom_rope_link_material">
        <color rgba="0.372549 0.654902 0.239216 1.0"/>
      </material>
    </visual>
    <!--<inertial>
      <origin xyz="-9.86505e-06 3.49992e-09 -0.310102" rpy="0 0 0"/>
      <mass value="0.0267926" />
      <inertia ixx="1.69419e-05" ixy="-1.44124e-12"  ixz="0.000129601" iyy="0.00101934" iyz="-9.97156e-13" izz="0.00100265" />
    </inertial>-->
  </link>

  <joint name="boom_rope_joint" type="fixed">
    <origin xyz="-0.4248 0 -0.02158" rpy="0 -0.721157 0" />
    <parent link="boom_link" />
    <child link="boom_rope_link" />
    <!--<axis xyz="0 0 1"/>-->
    <limit effort="50" velocity="10" />
    <joint_properties friction="0.0"/>
  </joint>

  <link name="camera_bow">
    <visual>
      <origin xyz="-2.03098 0 -0.125" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/camera_bow.stl"/>
      </geometry>
      <material name="camera_bow_material">
        <color rgba="0.501961 0.501961 0.501961 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.037 0 0.3675" rpy="0 0 0" />
      <geometry>
        <box size="${0.291+0.037} 0.198 0.735"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.0409132 -0.000229113 0.21045" rpy="0 0 0"/>
      <mass value="1.87478" />
      <inertia ixx="0.16504" ixy="-3.24877e-05"  ixz="-0.0376486" iyy="0.162383" iyz="-8.03763e-05" izz="0.0502642" />
    </inertial>
  </link>

  <joint name="camera_bow_joint" type="fixed">
    <origin xyz="2.03098 -6.93517e-15 0.125" rpy="0 0 0" />
    <parent link="deck_link" />
    <child link="camera_bow" />
    <!--<axis xyz="0 0 1"/>-->
    <limit effort="1" velocity="20" />
  </joint>

  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 1.5708 0" />
      <geometry>
        <cylinder length="0.02" radius="0.02"/>
      </geometry>
      <material name="camera_bow_material">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="${2.03098+0.180448} 0 ${0.645+0.125}" rpy="0 0 0" />
    <parent link="deck_link" />
    <child link="camera_link" />
  </joint>

  <link name="eletric_engine_base">
    <visual>
      <origin xyz="0 0 0" rpy="0 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/eletric_engine_base.stl"/>
      </geometry>
      <material name="eletric_engine_material"/>
    </visual>
    <inertial>
      <origin xyz="-0.0113138 9.61154e-18 0.109155" rpy="0 0 0"/>
      <mass value="1.07706" />
      <inertia ixx="0.00529253" ixy="0"  ixz="0.000628787" iyy="0.00431272" iyz="0" izz="0.00362977" />
    </inertial>
  </link>

  <joint name="eletric_egine_base" type="fixed">
    <origin xyz="-1.24471 1.33227e-15 0.199376" rpy="0 -0 0" />
    <parent link="hull_link" />
    <child link="eletric_engine_base" />
    <!--<axis xyz="0 0 1"/>-->
    <limit effort="1" velocity="20" />
    <joint_properties friction="0.0"/>
  </joint>

  <link name="eletric_engine_link">
    <visual>
      <origin xyz="0.08999 -7.65404e-19 -0.175" rpy="-1.26162e-16 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/eletric_engine.stl"/>
      </geometry>
      <material name="eletric_engine_material"/>
    </visual>
    <collision>
      <origin xyz="-0.02 0 ${-0.622+0.2}" rpy="0 0 0" />
      <geometry>
        <box size="0.236 0.113 1.244"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="-0.00825704 -3.56246e-09 -0.761657" rpy="0 0 0"/>
      <mass value="3.62539" />
      <inertia ixx="0.396803" ixy="-7.66434e-09"  ixz="-0.00560877" iyy="0.401013" iyz="-5.77582e-09" izz="0.00711339" />
    </inertial>
  </link>

  <link name="turbine_link">
    <visual>
      <origin xyz="0.179673 -9.07103e-17 0.774" rpy="0 -0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/turbine.stl"/>
      </geometry>
      <material name="turbine_material"/>
    </visual>
    <inertial>
      <origin xyz="-0.0280716 2.41471e-06 2.58598e-06" rpy="0 0 0"/>
      <mass value="0.0667546" />
      <inertia ixx="0.000104539" ixy="2.96574e-10"  ixz="-1.53341e-09" iyy="6.3824e-05" iyz="-2.26066e-09" izz="6.38236e-05" />
    </inertial>
  </link>

  <joint name="turbine_joint" type="continuous">
    <origin xyz="-0.089683 -7.7043e-18 -0.949" rpy="-1.26162e-16 -0 0" />
    <parent link="eletric_engine_link" />
    <child link="turbine_link" />
    <axis xyz="1 0 0"/>
    <limit effort="1000" velocity="20" />
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <joint name="eletric_engine_pose_joint" type="revolute">
    <origin xyz="-1.3347 1.33303e-15 0.374376" rpy="0 -0 0" />
    <parent link="hull_link" />
    <child link="eletric_engine_link" />
    <axis xyz="0 0 1"/>
    <limit effort="1" velocity="20" lower="0" upper="0"/>
    <joint_properties friction="0.0"/>
  </joint>

  <link name="camera_top">
    <visual>
      <origin xyz="0.053 0 -2.832" rpy="0 -0 0" />
      <geometry>
      <mesh filename="package://eboat_description/models/eboat/meshes/camera_top.stl"/>
      </geometry>
      <material name="camera_top_material">
      <color rgba="0.623529 0.666667 0.701961 1.0"/>
      </material>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0" />
      <inertia ixx="0" ixy="0"  ixz="0" iyy="0" iyz="0" izz="0" />
      </inertial>
  </link>

  <joint name="camera_top_joint" type="fixed">
    <origin xyz="-0.053 -2.14313e-18 3.765" rpy="0 0 0" />
    <parent link="mast_link" />
    <child link="camera_top" />
    <!--<axis xyz="0 0 1"/>-->
  </joint>

  <link name="biruta_link">
    <visual>
      <origin xyz="-0.161823 0 -2.832" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://eboat_description/models/eboat/meshes/biruta.stl"/>
      </geometry>
      <material name="biruta_material">
        <color rgba="0.647059 0.647059 0.647059 1.0"/>
      </material>
    </visual>
    <inertial>
      <origin xyz="-0.0148129 1.0796e-10 0.0419007" rpy="0 0 0"/>
      <mass value="0.0021539" />
      <inertia ixx="1.19286e-06" ixy="-1.19699e-14"  ixz="6.09373e-07" iyy="2.92342e-06" iyz="-4.59008e-15" izz="1.8198e-06" />
    </inertial>
  </link>

  <joint name="biruta_joint" type="continuous">
    <origin xyz="0.161823 -1.62266e-18 3.765" rpy="0 -0 0" />
    <parent link="mast_link" />
    <child link="biruta_link" />
    <axis xyz="0 0 1"/>
    <limit effort="1" velocity="2"/>
    <dynamics damping="0.0" friction="0.00002"/>
  </joint>


</robot>
